// generated by stringer -type=matchKind; DO NOT EDIT

package main

import "fmt"

const _matchKind_name = "matchNonematchPartialmatchExact"

var _matchKind_index = [...]uint8{0, 9, 21, 31}

func (i matchKind) String() string {
	if i < 0 || i+1 >= matchKind(len(_matchKind_index)) {
		return fmt.Sprintf("matchKind(%d)", i)
	}
	return _matchKind_name[_matchKind_index[i]:_matchKind_index[i+1]]
}
